'use client';import { useEffect, useState } from 'react';import api from '@/lib/api';import { Button } from '@/components/ui/button';import { Input } from '@/components/ui/input';import { Select,SelectContent,SelectItem,SelectTrigger,SelectValue } from '@/components/ui/select';import { toast } from '@/components/ui/toast';
export default function Page(){const [f,setF]=useState({autoCode:'',defaultTax:'',approvalRequired:true});const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);
useEffect(()=>{api.get('/purchase-params').then(r=>{const d=r.data;setF({autoCode:d.autoCode||'PO{yyyyMM}{seq:4}',defaultTax:d.defaultTax||'13',approvalRequired:d.approvalRequired!==false});setLoading(false);}).catch(()=>setLoading(false));},[]);
const save=async()=>{setSaving(true);try{await api.put('/purchase-params',f);toast('保存成功','success');}catch(e:any){toast(e.response?.data?.message||'保存失败','error');}finally{setSaving(false);}};
if(loading)return<div className="p-6 max-w-2xl"><div className="text-muted-foreground text-[13px]">加载中...</div></div>;
return(<div className="p-6 max-w-2xl"><div className="bg-background rounded-lg border p-6 space-y-4"><h1 className="text-lg font-bold">采购参数</h1>
<div className="space-y-3"><div><label className="text-[13px] font-medium">采购单编码规则</label><Input className="h-9 rounded-md border border-border bg-background px-3 text-[13px]" value={f.autoCode} onChange={e=>setF({...f,autoCode:e.target.value})}/></div>
<div><label className="text-[13px] font-medium">默认税率(%)</label><Input className="h-9 rounded-md border border-border bg-background px-3 text-[13px]" value={f.defaultTax} onChange={e=>setF({...f,defaultTax:e.target.value})}/></div>
<div><label className="text-[13px] font-medium">需要审批</label><Select value={f.approvalRequired?'true':'false'} onValueChange={(v:any)=>setF({...f,approvalRequired:v==='true'})}><SelectTrigger className="h-9 rounded-md border border-border bg-background px-3 text-[13px] w-full"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="true">是</SelectItem><SelectItem value="false">否</SelectItem></SelectContent></Select></div></div>
<div className="flex items-center gap-3"><Button size="sm" onClick={save} disabled={saving}>{saving?'保存中...':'保存'}</Button></div></div></div>);}
