'use client';
import { useRouter } from 'next/navigation';
import { useEffect, useState, useCallback } from 'react';
import api from '@/lib/api';
import { Button } from '@/components/ui/button'; import { Input } from '@/components/ui/input';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Checkbox } from '@/components/ui/checkbox';
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from '@/components/ui/alert-dialog';
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from '@/components/ui/tooltip';
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from '@/components/ui/dropdown-menu';
import { ChevronDown, Pencil, RefreshCw, Search, Settings, Trash2, Download, Upload } from 'lucide-react';

interface Item { id:string;returnNo:string;shipmentNo:string|null;customerName:string|null;totalQuantity:string|null;totalAmount:string|null;returnReason:string|null;approvalStatus:string;businessStatus:string;createdAt:string; }
const AP:Record<string,string>={DRAFT:'草稿',SUBMITTED:'已提交',APPROVED:'已通过',REJECTED:'已拒绝'};

export default function SalesReturnPage() {
  const [items,setItems]=useState<Item[]>([]);const [total,setTotal]=useState(0);const [pg,setPg]=useState(1);const [ps,setPs]=useState(30);
  const [sel,setSel]=useState<Set<string>>(new Set());const [s,setS]=useState({code:'',name:'',status:''});
  const [open,setOpen]=useState(false);const [ed,setEd]=useState<Item|null>(null);
  const [f,setF]=useState({returnNo:'',shipmentNo:'',customerName:'',totalQuantity:'',totalAmount:'',returnReason:''});
  const [del,setDel]=useState<string|null>(null);

  const fetch=useCallback(async()=>{
    const p:any={page:pg,pageSize:ps}; if(s.code)p.code=s.code; if(s.name)p.name=s.name; if(s.status)p.status=s.status;
    const {data}=await api.get('/sales-returns',{params:p}); setItems(data.items); setTotal(data.total);
  },[pg,ps,s]); useEffect(()=>{fetch();},[fetch]);

  const add=()=>{setEd(null);setF({returnNo:'',shipmentNo:'',customerName:'',totalQuantity:'',totalAmount:'',returnReason:''});setOpen(true);};
  const edit=(i:Item)=>{setEd(i);setF({returnNo:i.returnNo,shipmentNo:i.shipmentNo||'',customerName:i.customerName||'',totalQuantity:i.totalQuantity||'',totalAmount:i.totalAmount||'',returnReason:i.returnReason||''});setOpen(true);};
  const save=async()=>{try{const d={...f,totalQuantity:f.totalQuantity?+f.totalQuantity:null,totalAmount:f.totalAmount?+f.totalAmount:null};await (ed?api.put(`/sales-returns/${ed.id}`,d):api.post('/sales-returns',d));setOpen(false);fetch();}catch(e:any){alert(e.response?.data?.message||'保存失败');}};
  const doDel=async()=>{if(!del)return;await api.delete(`/sales-returns/${del}`);setDel(null);fetch();};
  const tp=Math.ceil(total/ps);const pgs=Array.from({length:tp},(_,i)=>i+1).filter(p=>p===1||p===tp||Math.abs(p-pg)<=2);

  return (<TooltipProvider><div className="h-full flex flex-col bg-white">
    <div className="flex items-center justify-between px-4 py-2 border-b border-gray-100"><div className="flex items-center gap-1"><Button size="sm" onClick={add}><span className="mr-1">+</span>新增</Button><Button size="sm" variant="outline" disabled={sel.size===0}>修改</Button><Button size="sm" variant="outline" disabled={sel.size===0}>删除</Button><DropdownMenu><DropdownMenuTrigger asChild><Button size="sm" variant="outline">导入 <ChevronDown size={12} className="ml-1"/></Button></DropdownMenuTrigger><DropdownMenuContent><DropdownMenuItem><Upload size={14} className="mr-2"/>导入数据</DropdownMenuItem></DropdownMenuContent></DropdownMenu><Button size="sm" variant="outline"><Download size={14} className="mr-1"/>导出</Button></div><div className="flex items-center gap-1"><Button size="sm" variant="ghost" onClick={()=>setS({code:'',name:'',status:''})}>重置</Button><Button size="sm" onClick={fetch}><Search size={14} className="mr-1"/>搜索</Button></div></div>
    <div className="flex items-center gap-3 px-4 py-2.5 bg-gray-50/50 border-b border-gray-100 flex-wrap">
      <F label="状态"><Select value={s.status} onValueChange={v=>setS({...s,status:v==='ALL'?'':v})}><SelectTrigger className="w-[90px] h-8 text-[12px]"><SelectValue placeholder="全部"/></SelectTrigger><SelectContent><SelectItem value="ALL">全部</SelectItem><SelectItem value="DRAFT">草稿</SelectItem><SelectItem value="SUBMITTED">已提交</SelectItem><SelectItem value="APPROVED">已通过</SelectItem></SelectContent></Select></F>
      <F label="退货单号"><Input className="w-[140px] h-8 text-[12px]" value={s.code} onChange={e=>setS({...s,code:e.target.value})}/></F>
      <F label="客户"><Input className="w-[130px] h-8 text-[12px]" value={s.name} onChange={e=>setS({...s,name:e.target.value})}/></F>
    </div>
    <div className="flex-1 overflow-auto"><div className="flex items-center justify-end px-4 py-1.5 bg-gray-50/30 border-b border-gray-100 gap-1"><Tooltip><TooltipTrigger asChild><button className="p-1.5 hover:bg-gray-100 rounded text-gray-400 hover:text-gray-600"><RefreshCw size={14}/></button></TooltipTrigger><TooltipContent>刷新</TooltipContent></Tooltip><Tooltip><TooltipTrigger asChild><button className="p-1.5 hover:bg-gray-100 rounded text-gray-400 hover:text-gray-600"><Settings size={14}/></button></TooltipTrigger><TooltipContent>列设置</TooltipContent></Tooltip></div>
    <table className="w-full text-[13px]"><thead className="bg-gray-50 border-y border-gray-200 sticky top-0"><tr><th className="w-10 px-3 py-2.5"><Checkbox/></th><th className="text-left px-2 py-2.5 font-medium text-gray-600">审批状态</th><th className="text-left px-2 py-2.5 font-medium text-gray-600">退货单号</th><th className="text-left px-2 py-2.5 font-medium text-gray-600">关联出货</th><th className="text-left px-2 py-2.5 font-medium text-gray-600">客户</th><th className="text-left px-2 py-2.5 font-medium text-gray-600">数量</th><th className="text-left px-2 py-2.5 font-medium text-gray-600">金额</th><th className="text-left px-2 py-2.5 font-medium text-gray-600">退货原因</th><th className="text-left px-2 py-2.5 font-medium text-gray-600">创建时间</th><th className="text-left px-2 py-2.5 font-medium text-gray-600">操作</th></tr></thead><tbody>
    {items.map(i=>(<tr key={i.id} className="border-b border-gray-100 hover:bg-blue-50/30"><td className="px-3 py-2.5"><Checkbox/></td><td className="px-2 py-2.5"><span className={`inline-flex px-1 py-0.5 rounded text-[11px] ${i.approvalStatus==='APPROVED'?'bg-green-50 text-green-700':i.approvalStatus==='SUBMITTED'?'bg-blue-50 text-blue-700':'bg-gray-50 text-gray-500'}`}>{AP[i.approvalStatus]}</span></td><td className="px-2 py-2.5"><button className="text-blue-600 hover:text-blue-800 hover:underline text-[13px]">{i.returnNo}</button></td><td className="px-2 py-2.5 text-gray-500">{i.shipmentNo||'-'}</td><td className="px-2 py-2.5 text-gray-700">{i.customerName||'-'}</td><td className="px-2 py-2.5 text-gray-700">{i.totalQuantity||'-'}</td><td className="px-2 py-2.5 text-gray-700">{i.totalAmount?Number(i.totalAmount).toLocaleString():'-'}</td><td className="px-2 py-2.5 text-gray-500">{i.returnReason||'-'}</td><td className="px-2 py-2.5 text-gray-500 text-[12px]">{new Date(i.createdAt).toLocaleDateString('zh-CN')}</td><td className="px-2 py-2.5"><div className="flex items-center gap-2"><button onClick={()=>edit(i)} className="text-blue-600 hover:text-blue-800 text-[12px]"><Pencil size={12} className="inline mr-0.5"/>修改</button>{i.approvalStatus==='DRAFT'&&<button onClick={()=>{api.put(`/sales-returns/${i.id}/submit`).then(fetch);}} className="text-blue-600 text-[12px]">提交</button>}<button onClick={()=>setDel(i.id)} className="text-red-500 hover:text-red-700 text-[12px]"><Trash2 size={12} className="inline mr-0.5"/>删除</button></div></td></tr>))}
    {items.length===0&&<tr><td colSpan={10} className="text-center text-gray-400 py-16">暂无数据</td></tr>}
    </tbody></table></div>
    <div className="flex items-center justify-between px-4 py-2.5 border-t border-gray-200 bg-white shrink-0"><span className="text-[12px] text-gray-500">共 {total} 条</span><div className="flex items-center gap-3"><Select value={String(ps)} onValueChange={v=>{setPs(+v);setPg(1);}}><SelectTrigger className="w-[100px] h-8 text-[12px]"><SelectValue/></SelectTrigger><SelectContent>{[20,30,50,100].map(n=><SelectItem key={n} value={String(n)}>{n}条/页</SelectItem>)}</SelectContent></Select><div className="flex items-center gap-0.5"><Button size="sm" variant="ghost" disabled={pg<=1} onClick={()=>setPg(p=>p-1)} className="text-[12px] px-2">‹</Button>{pgs.map((p,i)=>(<span key={p}>{i>0&&pgs[i-1]!==p-1&&<span className="text-gray-300 mx-0.5">...</span>}<button onClick={()=>setPg(p)} className={`w-7 h-7 rounded text-[12px] transition-colors ${p===pg?'bg-blue-600 text-white':'text-gray-600 hover:bg-gray-100'}`}>{p}</button></span>))}<Button size="sm" variant="ghost" disabled={pg>=tp} onClick={()=>setPg(p=>p+1)} className="text-[12px] px-2">›</Button></div></div></div>

    <Dialog open={open} onOpenChange={setOpen}><DialogContent className="max-w-lg"><DialogHeader><DialogTitle>{ed?'修改销售退货':'新增销售退货'}</DialogTitle></DialogHeader><div className="space-y-3 max-h-[60vh] overflow-y-auto py-2"><div className="grid grid-cols-2 gap-3"><div><label className="text-[12px] font-medium">退货单号 *</label><Input className="h-8 text-[13px]" value={f.returnNo} onChange={e=>setF({...f,returnNo:e.target.value})} disabled={!!ed}/></div><div><label className="text-[12px] font-medium">关联出货</label><Input className="h-8 text-[13px]" value={f.shipmentNo} onChange={e=>setF({...f,shipmentNo:e.target.value})}/></div><div><label className="text-[12px] font-medium">客户</label><Input className="h-8 text-[13px]" value={f.customerName} onChange={e=>setF({...f,customerName:e.target.value})}/></div><div><label className="text-[12px] font-medium">数量</label><Input type="number" className="h-8 text-[13px]" value={f.totalQuantity} onChange={e=>setF({...f,totalQuantity:e.target.value})}/></div><div><label className="text-[12px] font-medium">金额</label><Input type="number" className="h-8 text-[13px]" value={f.totalAmount} onChange={e=>setF({...f,totalAmount:e.target.value})}/></div><div><label className="text-[12px] font-medium">退货原因</label><Input className="h-8 text-[13px]" value={f.returnReason} onChange={e=>setF({...f,returnReason:e.target.value})}/></div></div></div><DialogFooter><Button variant="outline" size="sm" onClick={()=>setOpen(false)}>取消</Button><Button size="sm" onClick={save}>确定</Button></DialogFooter></DialogContent></Dialog>
    <AlertDialog open={!!del} onOpenChange={()=>setDel(null)}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>确认删除？</AlertDialogTitle></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>取消</AlertDialogCancel><AlertDialogAction onClick={doDel} className="bg-red-600 hover:bg-red-700">删除</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
  </div></TooltipProvider>);
}
function F({label,children}:{label:string;children:React.ReactNode}){return<div className="flex items-center gap-1.5"><span className="text-[12px] text-gray-500">{label}</span>{children}</div>;}
